### PR TITLE
fix: performance improvement and shuffling limited queries

### PR DESCRIPTION
**Pull request by sandros94**
The original `shuffleArray` and `getRandomItems` functions had a quadratic performance, mainly caused by `splice` in the loop, resulting in a $O(n^2)$ performance ($n$ being the number of items to shuffle).
With the these updated ones (credit to this awesome blog post about [Fisher-Yates Shuffle](https://bost.ocks.org/mike/shuffle/)) we get a much better linear performance of $O(n)$. Crucial when shuffling medium to big collections.

This also fixes the fact that when doing a limited query, the output would have still being sorted by `id`s in alphanumeric order.

### Detailed Explanation
A slightly in-depth explanation on the performance improvement that this PR introduces (mainly discussed privately on Discord):

>`splice` on its own has a performance of `O(n)`, doing a for loop on an array has also a performance of `O(n)`. The sum thus is `O(n^2)`. Removing the usage of `splice` (thus editing the array inplace, without an additional array) makes us achieve `O(n)` performance in `shuffleArray`.
>
>For `getRandomItems` its a similar story, the original one, using `splice` achieve a performance of a minimum of `O(amount*n)` and a maximum of `O(n^2)`, but if we remove `splice` we go down to a minimum of `O(amount)` and a maximum of `O(n)`. But since we only picked a random set, without truly shuffling it, we need to add a `shuffleArray` making it in the end a performance between `O(amount^2)` and a maximum of `O(n^2)`

### CODE REVIEW

**Comment by br41nslug** [comment]
As you may be able to guess this extension was not made with performance in mind (or production use for that matter). But i won't say no to a free performance improvement so will have a look at it later 🚀.

**Comment by sandros94** [comment]
> As you may be able to guess this extension was not made with performance in mind (or production use for that matter).

Oh I'm 100% aware of that! But since you mentioned it in [directus/#3240](https://github.com/directus/directus/discussions/3240#discussioncomment-3643088) I wanted to contribute to this nice _example_. 😁

> But i won't say no to a free performance improvement so will have a look at it later 🚀.

This is actually my first time placing my hands on a Directus extension, but I shouldn't have made a mess 😜

**Comment by sandros94** [comment]
I've noticed a small mistake in `getRandomItems`, I'm fixing it right now.

**Review by br41nslug — APPROVED** [review]
Great addition, this shuffle algorithm is measurably more efficient 🚀

**Pull request merged**
